import { join } from 'node:path';

import { curatedItemMetaJsonSchema, type ImportableContentType } from '@english-quest/shared';

import type { LoadedErrorTaxonomy } from '../taxonomy/error-taxonomy';
import { META_SCHEMA_FILE } from './content-constants';

type JsonObject = Record<string, unknown>;

/**
 * The editor-facing JSON Schema for one type's `meta.json`, generated from the
 * shared Zod schema so there is nothing to keep in sync by hand. It flags
 * shape errors while the curator drafts; cross-field rules (the answer key,
 * type-dependent skills) are refinements JSON Schema cannot express, so only
 * the importer catches those.
 *
 * `target_tags.items` gets an `enum` of the taxonomy in force, which gives
 * autocompletion on exactly the tags the importer will accept, and couples
 * these files to the taxonomy: `content-meta-schema-snapshot.spec.ts` fails
 * until `pnpm content:schema` is re-run after a taxonomy change.
 */
export function buildMetaSchema(type: ImportableContentType, taxonomy: LoadedErrorTaxonomy): JsonObject {
  const generated = curatedItemMetaJsonSchema(type);
  const { $schema, ...rest } = generated;
  const properties = rest.properties as Record<string, JsonObject>;
  const targetTags = properties.target_tags;
  if (!targetTags) {
    throw new Error(`The ${type} meta schema has no target_tags property.`);
  }

  properties.target_tags = {
    ...targetTags,
    description: `Error taxonomy tags this item trains, from apps/api/rules/error-taxonomy.yaml (v${taxonomy.version})`,
    items: { ...(targetTags.items as JsonObject), enum: taxonomy.tags.map((tag) => tag.tag) },
  };

  return {
    $schema,
    $comment: 'Generated by `pnpm content:schema` from @english-quest/shared and the error taxonomy. Do not edit by hand.',
    title: `English Quest ${type} item (meta.json)`,
    ...rest,
  };
}

export function metaSchemaPath(root: string, type: ImportableContentType): string {
  return join(root, type, META_SCHEMA_FILE);
}

export function renderMetaSchema(schema: JsonObject): string {
  return `${JSON.stringify(schema, null, 2)}\n`;
}
