name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  connectivity_plus: ^7.3.1
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_modular: ^7.1.0
  flutter_secure_storage: ^11.1.1
  get: ^4.7.3
  record: ^7.1.1
  shared_preferences: ^2.5.5
  english_quest_tokens:
    path: ../../packages/design-tokens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
