export {
  ERROR_CODES,
  ERROR_MESSAGES,
  ERROR_STATUS,
  type ErrorCode,
} from './errors/codes';

export {
  isApiError,
  type ApiError,
  type ApiResponse,
  type ApiSuccess,
  type DependencyHealth,
  type HealthReport,
  type ValidationDetail,
} from './types/api';

export {
  apiKeyField,
  azureRegionField,
  credentialProviderSchema,
  credentialStatusSchema,
  maskedCredentialListSchema,
  maskedCredentialSchema,
  providerLabels,
  saveCredentialSchema,
  type CredentialProvider,
  type CredentialStatus,
  type MaskedCredential,
  type SaveCredentialInput,
} from './schemas/credentials';

export {
  apiErrorSchema,
  dependencyHealthSchema,
  healthReportSchema,
  validationDetailSchema,
} from './schemas/api';

export {
  changePasswordSchema,
  currentUserSchema,
  emailField,
  loginSchema,
  newPasswordField,
  passwordField,
  publicUserSchema,
  sessionTokenSchema,
  type ChangePasswordInput,
  type CurrentUser,
  type LoginInput,
  type PublicUser,
  type SessionTokenResponse,
} from './schemas/auth';

export {
  classroomAwaitingSchema,
  classroomEndResultSchema,
  classroomParticipantSchema,
  classroomSessionSchema,
  classroomTokenSchema,
  lessonEndReasonSchema,
  lessonStatusSchema,
  type ClassroomAwaiting,
  type ClassroomEndResult,
  type ClassroomParticipant,
  type ClassroomSession,
  type ClassroomToken,
  type LessonEndReason,
  type LessonStatus,
} from './schemas/classroom';

export {
  lessonRecordingStatusSchema,
  lessonRecordingViewSchema,
  liveParticipantRecordingStatusSchema,
  liveRecordingSchema,
  liveRecordingStatusSchema,
  participantRecordingStatusSchema,
  pipelineBranchStageSchema,
  pipelineBranchStatusSchema,
  pipelineBranchViewSchema,
  recordingFailureCodeSchema,
  type LessonRecordingStatus,
  type LessonRecordingView,
  type LiveParticipantRecordingStatus,
  type LiveRecording,
  type LiveRecordingStatus,
  type ParticipantRecordingStatus,
  type PipelineBranchStage,
  type PipelineBranchStatus,
  type PipelineBranchView,
  type RecordingFailureCode,
} from './schemas/recording';

export {
  lessonScenarioStatusSchema,
  lessonScenarioViewSchema,
  registerSchema,
  roleCardSchema,
  roleCardStatusSchema,
  roleSchema,
  scenarioStatusSchema,
  scenarioViewSchema,
  sharedSituationSchema,
  vocabularyDomainSchema,
  type LessonScenarioStatus,
  type LessonScenarioView,
  type Register,
  type Role,
  type RoleCard,
  type RoleCardStatus,
  type ScenarioStatus,
  type ScenarioView,
  type SharedSituation,
  type VocabularyDomain,
} from './schemas/scenario';

export {
  analysisFailureCodeSchema,
  blockedReasonCodeSchema,
  branchFailureCodeSchema,
  lessonPipelineViewSchema,
  pipelineReasonCodeSchema,
  pipelineStageLabels,
  pipelineStageSchema,
  pipelineStageStatusSchema,
  pipelineStageViewSchema,
  pronunciationFailureCodeSchema,
  stageFailureCodeSchema,
  transcriptionFailureCodeSchema,
  type AnalysisFailureCode,
  type BlockedReasonCode,
  type BranchFailureCode,
  type LessonPipelineView,
  type PipelineReasonCode,
  type PipelineStage,
  type PipelineStageStatus,
  type PipelineStageView,
  type PronunciationFailureCode,
  type StageFailureCode,
  type TranscriptionFailureCode,
} from './schemas/pipeline';

export {
  lessonTranscriptViewSchema,
  transcriptSpeakerSchema,
  transcriptSpeakerStatusSchema,
  transcriptUtteranceSchema,
  transcriptWordSchema,
  type LessonTranscriptView,
  type TranscriptSpeaker,
  type TranscriptSpeakerStatus,
  type TranscriptUtterance,
  type TranscriptWord,
} from './schemas/transcript';

export {
  excerptSelectionSummarySchema,
  transcriptExcerptSchema,
  type ExcerptSelectionSummary,
  type TranscriptExcerpt,
} from './schemas/excerpt';

export {
  assessedWordSchema,
  excerptPronunciationSchema,
  excerptPronunciationStatusSchema,
  lessonPronunciationResultSchema,
  lessonPronunciationStatusSchema,
  lessonPronunciationViewSchema,
  pronunciationExcerptViewSchema,
  pronunciationOverallSchema,
  pronunciationScoresSchema,
  pronunciationWordBandSchema,
  worstPhonemeSchema,
  worstWordSchema,
  type AssessedWord,
  type ExcerptPronunciation,
  type ExcerptPronunciationStatus,
  type LessonPronunciationResult,
  type LessonPronunciationStatus,
  type LessonPronunciationView,
  type PronunciationExcerptView,
  type PronunciationOverall,
  type PronunciationScores,
  type PronunciationWordBand,
  type WorstPhoneme,
  type WorstWord,
} from './schemas/pronunciation';

export {
  analysisCompetencySchema,
  analysisCompetencyViewSchema,
  analysisErrorViewSchema,
  correctionSegmentSchema,
  errorRecurrenceSchema,
  errorSeveritySchema,
  lessonAnalysisResultSchema,
  lessonAnalysisStatusSchema,
  lessonAnalysisViewSchema,
  scenarioContextSchema,
  scenarioFitViewSchema,
  type AnalysisCompetency,
  type AnalysisCompetencyView,
  type AnalysisErrorView,
  type CorrectionSegment,
  type ErrorRecurrence,
  type ErrorSeverity,
  type LessonAnalysisResult,
  type LessonAnalysisStatus,
  type LessonAnalysisView,
  type ScenarioContext,
  type ScenarioFitView,
} from './schemas/analysis';

export {
  LESSON_LIST_DEFAULT_LIMIT,
  LESSON_LIST_MAX_LIMIT,
  lessonDetailViewSchema,
  lessonHistoryFlagLabels,
  lessonHistoryFlagSchema,
  lessonHistoryStatusLabels,
  lessonHistoryStatusSchema,
  lessonListQuerySchema,
  lessonListSchema,
  lessonParticipantSummarySchema,
  lessonScenarioStepSchema,
  lessonSummarySchema,
  otherParticipantProcessingSchema,
  otherParticipantStageSchema,
  participantStageStateSchema,
  type LessonDetailView,
  type LessonHistoryFlag,
  type LessonHistoryStatus,
  type LessonList,
  type LessonListQuery,
  type LessonParticipantSummary,
  type LessonScenarioStep,
  type LessonSummary,
  type OtherParticipantProcessing,
  type OtherParticipantStage,
  type ParticipantStageState,
} from './schemas/lessons';
